// Code generated by ogen, DO NOT EDIT.
package oas

// AddStickerToSetRes represents addStickerToSet response.
type AddStickerToSetRes interface {
	addStickerToSetRes()
}

// AnswerCallbackQueryRes represents answerCallbackQuery response.
type AnswerCallbackQueryRes interface {
	answerCallbackQueryRes()
}

// AnswerInlineQueryRes represents answerInlineQuery response.
type AnswerInlineQueryRes interface {
	answerInlineQueryRes()
}

// AnswerPreCheckoutQueryRes represents answerPreCheckoutQuery response.
type AnswerPreCheckoutQueryRes interface {
	answerPreCheckoutQueryRes()
}

// AnswerShippingQueryRes represents answerShippingQuery response.
type AnswerShippingQueryRes interface {
	answerShippingQueryRes()
}

// BanChatMemberRes represents banChatMember response.
type BanChatMemberRes interface {
	banChatMemberRes()
}

// CopyMessageRes represents copyMessage response.
type CopyMessageRes interface {
	copyMessageRes()
}

// CreateChatInviteLinkRes represents createChatInviteLink response.
type CreateChatInviteLinkRes interface {
	createChatInviteLinkRes()
}

// CreateNewStickerSetRes represents createNewStickerSet response.
type CreateNewStickerSetRes interface {
	createNewStickerSetRes()
}

// DeleteChatPhotoRes represents deleteChatPhoto response.
type DeleteChatPhotoRes interface {
	deleteChatPhotoRes()
}

// DeleteChatStickerSetRes represents deleteChatStickerSet response.
type DeleteChatStickerSetRes interface {
	deleteChatStickerSetRes()
}

// DeleteMessageRes represents deleteMessage response.
type DeleteMessageRes interface {
	deleteMessageRes()
}

// DeleteMyCommandsRes represents deleteMyCommands response.
type DeleteMyCommandsRes interface {
	deleteMyCommandsRes()
}

// DeleteStickerFromSetRes represents deleteStickerFromSet response.
type DeleteStickerFromSetRes interface {
	deleteStickerFromSetRes()
}

// DeleteWebhookRes represents deleteWebhook response.
type DeleteWebhookRes interface {
	deleteWebhookRes()
}

// EditChatInviteLinkRes represents editChatInviteLink response.
type EditChatInviteLinkRes interface {
	editChatInviteLinkRes()
}

// EditMessageCaptionRes represents editMessageCaption response.
type EditMessageCaptionRes interface {
	editMessageCaptionRes()
}

// EditMessageLiveLocationRes represents editMessageLiveLocation response.
type EditMessageLiveLocationRes interface {
	editMessageLiveLocationRes()
}

// EditMessageMediaRes represents editMessageMedia response.
type EditMessageMediaRes interface {
	editMessageMediaRes()
}

// EditMessageReplyMarkupRes represents editMessageReplyMarkup response.
type EditMessageReplyMarkupRes interface {
	editMessageReplyMarkupRes()
}

// EditMessageTextRes represents editMessageText response.
type EditMessageTextRes interface {
	editMessageTextRes()
}

// ExportChatInviteLinkRes represents exportChatInviteLink response.
type ExportChatInviteLinkRes interface {
	exportChatInviteLinkRes()
}

// ForwardMessageRes represents forwardMessage response.
type ForwardMessageRes interface {
	forwardMessageRes()
}

// GetChatAdministratorsRes represents getChatAdministrators response.
type GetChatAdministratorsRes interface {
	getChatAdministratorsRes()
}

// GetChatMemberCountRes represents getChatMemberCount response.
type GetChatMemberCountRes interface {
	getChatMemberCountRes()
}

// GetChatMemberRes represents getChatMember response.
type GetChatMemberRes interface {
	getChatMemberRes()
}

// GetChatRes represents getChat response.
type GetChatRes interface {
	getChatRes()
}

// GetFileRes represents getFile response.
type GetFileRes interface {
	getFileRes()
}

// GetGameHighScoresRes represents getGameHighScores response.
type GetGameHighScoresRes interface {
	getGameHighScoresRes()
}

// GetMeRes represents getMe response.
type GetMeRes interface {
	getMeRes()
}

// GetMyCommandsRes represents getMyCommands response.
type GetMyCommandsRes interface {
	getMyCommandsRes()
}

// GetStickerSetRes represents getStickerSet response.
type GetStickerSetRes interface {
	getStickerSetRes()
}

// GetUpdatesRes represents getUpdates response.
type GetUpdatesRes interface {
	getUpdatesRes()
}

// GetUserProfilePhotosRes represents getUserProfilePhotos response.
type GetUserProfilePhotosRes interface {
	getUserProfilePhotosRes()
}

// LeaveChatRes represents leaveChat response.
type LeaveChatRes interface {
	leaveChatRes()
}

// PinChatMessageRes represents pinChatMessage response.
type PinChatMessageRes interface {
	pinChatMessageRes()
}

// PromoteChatMemberRes represents promoteChatMember response.
type PromoteChatMemberRes interface {
	promoteChatMemberRes()
}

// RestrictChatMemberRes represents restrictChatMember response.
type RestrictChatMemberRes interface {
	restrictChatMemberRes()
}

// RevokeChatInviteLinkRes represents revokeChatInviteLink response.
type RevokeChatInviteLinkRes interface {
	revokeChatInviteLinkRes()
}

// SendAnimationRes represents sendAnimation response.
type SendAnimationRes interface {
	sendAnimationRes()
}

// SendAudioRes represents sendAudio response.
type SendAudioRes interface {
	sendAudioRes()
}

// SendChatActionRes represents sendChatAction response.
type SendChatActionRes interface {
	sendChatActionRes()
}

// SendContactRes represents sendContact response.
type SendContactRes interface {
	sendContactRes()
}

// SendDiceRes represents sendDice response.
type SendDiceRes interface {
	sendDiceRes()
}

// SendDocumentRes represents sendDocument response.
type SendDocumentRes interface {
	sendDocumentRes()
}

// SendGameRes represents sendGame response.
type SendGameRes interface {
	sendGameRes()
}

// SendInvoiceRes represents sendInvoice response.
type SendInvoiceRes interface {
	sendInvoiceRes()
}

// SendLocationRes represents sendLocation response.
type SendLocationRes interface {
	sendLocationRes()
}

// SendMediaGroupRes represents sendMediaGroup response.
type SendMediaGroupRes interface {
	sendMediaGroupRes()
}

// SendMessageRes represents sendMessage response.
type SendMessageRes interface {
	sendMessageRes()
}

// SendPhotoRes represents sendPhoto response.
type SendPhotoRes interface {
	sendPhotoRes()
}

// SendPollRes represents sendPoll response.
type SendPollRes interface {
	sendPollRes()
}

// SendStickerRes represents sendSticker response.
type SendStickerRes interface {
	sendStickerRes()
}

// SendVenueRes represents sendVenue response.
type SendVenueRes interface {
	sendVenueRes()
}

// SendVideoNoteRes represents sendVideoNote response.
type SendVideoNoteRes interface {
	sendVideoNoteRes()
}

// SendVideoRes represents sendVideo response.
type SendVideoRes interface {
	sendVideoRes()
}

// SendVoiceRes represents sendVoice response.
type SendVoiceRes interface {
	sendVoiceRes()
}

// SetChatAdministratorCustomTitleRes represents setChatAdministratorCustomTitle response.
type SetChatAdministratorCustomTitleRes interface {
	setChatAdministratorCustomTitleRes()
}

// SetChatDescriptionRes represents setChatDescription response.
type SetChatDescriptionRes interface {
	setChatDescriptionRes()
}

// SetChatPermissionsRes represents setChatPermissions response.
type SetChatPermissionsRes interface {
	setChatPermissionsRes()
}

// SetChatPhotoRes represents setChatPhoto response.
type SetChatPhotoRes interface {
	setChatPhotoRes()
}

// SetChatStickerSetRes represents setChatStickerSet response.
type SetChatStickerSetRes interface {
	setChatStickerSetRes()
}

// SetChatTitleRes represents setChatTitle response.
type SetChatTitleRes interface {
	setChatTitleRes()
}

// SetGameScoreRes represents setGameScore response.
type SetGameScoreRes interface {
	setGameScoreRes()
}

// SetMyCommandsRes represents setMyCommands response.
type SetMyCommandsRes interface {
	setMyCommandsRes()
}

// SetPassportDataErrorsRes represents setPassportDataErrors response.
type SetPassportDataErrorsRes interface {
	setPassportDataErrorsRes()
}

// SetStickerPositionInSetRes represents setStickerPositionInSet response.
type SetStickerPositionInSetRes interface {
	setStickerPositionInSetRes()
}

// SetStickerSetThumbRes represents setStickerSetThumb response.
type SetStickerSetThumbRes interface {
	setStickerSetThumbRes()
}

// SetWebhookRes represents setWebhook response.
type SetWebhookRes interface {
	setWebhookRes()
}

// StopMessageLiveLocationRes represents stopMessageLiveLocation response.
type StopMessageLiveLocationRes interface {
	stopMessageLiveLocationRes()
}

// StopPollRes represents stopPoll response.
type StopPollRes interface {
	stopPollRes()
}

// UnbanChatMemberRes represents unbanChatMember response.
type UnbanChatMemberRes interface {
	unbanChatMemberRes()
}

// UnpinAllChatMessagesRes represents unpinAllChatMessages response.
type UnpinAllChatMessagesRes interface {
	unpinAllChatMessagesRes()
}

// UnpinChatMessageRes represents unpinChatMessage response.
type UnpinChatMessageRes interface {
	unpinChatMessageRes()
}

// UploadStickerFileRes represents uploadStickerFile response.
type UploadStickerFileRes interface {
	uploadStickerFileRes()
}
