// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"math"
	"net"
	"net/http"
	"net/url"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/json"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// No-op definition for keeping imports.
var (
	_ = context.Background()
	_ = fmt.Stringer(nil)
	_ = strings.Builder{}
	_ = errors.Is
	_ = sort.Ints
	_ = chi.Context{}
	_ = http.MethodGet
	_ = io.Copy
	_ = json.Marshal
	_ = bytes.NewReader
	_ = strconv.ParseInt
	_ = time.Time{}
	_ = conv.ToInt32
	_ = uuid.UUID{}
	_ = uri.PathEncoder{}
	_ = url.URL{}
	_ = math.Mod
	_ = validate.Int{}
	_ = ht.NewRequest
	_ = net.IP{}
)

type AddStickerToSet struct{}

type AnswerCallbackQuery struct{}

type AnswerInlineQuery struct{}

type AnswerPreCheckoutQuery struct{}

type AnswerShippingQuery struct{}

type BanChatMember struct{}

// ChatPermissions describes #/components/schemas/ChatPermissions.
type ChatPermissions struct {
	CanAddWebPagePreviews OptBool `json:"can_add_web_page_previews"`
	CanChangeInfo         OptBool `json:"can_change_info"`
	CanInviteUsers        OptBool `json:"can_invite_users"`
	CanPinMessages        OptBool `json:"can_pin_messages"`
	CanSendMediaMessages  OptBool `json:"can_send_media_messages"`
	CanSendMessages       OptBool `json:"can_send_messages"`
	CanSendOtherMessages  OptBool `json:"can_send_other_messages"`
	CanSendPolls          OptBool `json:"can_send_polls"`
}

type CopyMessage struct{}

type CreateChatInviteLink struct{}

type CreateNewStickerSet struct{}

type DeleteChatPhoto struct{}

type DeleteChatStickerSet struct{}

type DeleteMessage struct{}

type DeleteMyCommands struct{}

type DeleteStickerFromSet struct{}

type DeleteWebhook struct{}

type EditChatInviteLink struct{}

type EditMessageCaption struct{}

type EditMessageLiveLocation struct{}

type EditMessageMedia struct{}

type EditMessageReplyMarkup struct{}

type EditMessageText struct{}

type ExportChatInviteLink struct{}

type ForwardMessage struct{}

type GetChat struct{}

type GetChatAdministrators struct{}

type GetChatMember struct{}

type GetChatMemberCount struct{}

type GetFile struct{}

type GetGameHighScores struct{}

type GetMyCommands struct{}

type GetStickerSet struct{}

type GetUpdates struct{}

type GetUserProfilePhotos struct{}

type InlineKeyboardMarkup struct{}

type LeaveChat struct{}

// MaskPosition describes #/components/schemas/MaskPosition.
type MaskPosition struct {
	Point  string  `json:"point"`
	Scale  float64 `json:"scale"`
	XShift float64 `json:"x_shift"`
	YShift float64 `json:"y_shift"`
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

type PinChatMessage struct{}

type PromoteChatMember struct{}

type RestrictChatMember struct{}

type RevokeChatInviteLink struct{}

type SendAnimation struct{}

type SendAudio struct{}

type SendChatAction struct{}

type SendContact struct{}

type SendDice struct{}

type SendDocument struct{}

type SendGame struct{}

type SendInvoice struct{}

type SendLocation struct{}

type SendMediaGroup struct{}

type SendMessage struct{}

type SendPhoto struct{}

type SendPoll struct{}

type SendSticker struct{}

type SendVenue struct{}

type SendVideo struct{}

type SendVideoNote struct{}

type SendVoice struct{}

type SetChatAdministratorCustomTitle struct{}

type SetChatDescription struct{}

type SetChatPermissions struct{}

type SetChatPhoto struct{}

type SetChatStickerSet struct{}

type SetChatTitle struct{}

type SetGameScore struct{}

type SetMyCommands struct{}

type SetPassportDataErrors struct{}

type SetStickerPositionInSet struct{}

type SetStickerSetThumb struct{}

type SetWebhook struct{}

type StopMessageLiveLocation struct{}

type StopPoll struct{}

type UnbanChatMember struct{}

type UnpinAllChatMessages struct{}

type UnpinChatMessage struct{}

type UploadStickerFile struct{}

// User describes #/components/schemas/User.
type User struct {
	CanJoinGroups           OptBool   `json:"can_join_groups"`
	CanReadAllGroupMessages OptBool   `json:"can_read_all_group_messages"`
	FirstName               string    `json:"first_name"`
	ID                      int       `json:"id"`
	IsBot                   bool      `json:"is_bot"`
	LanguageCode            OptString `json:"language_code"`
	LastName                OptString `json:"last_name"`
	SupportsInlineQueries   OptBool   `json:"supports_inline_queries"`
	Username                OptString `json:"username"`
}
