name: Coverage
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Download dependencies
        run: go mod download

      - name: Run tests with coverage
        run: make coverage

      - name: Send coverage
        uses: codecov/codecov-action@v5
        with:
          files: profile.out
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
