name: Regenerate schema files

on:
  workflow_dispatch:

jobs:
  regenerate-schema:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout latest code
        uses: actions/checkout@v3.1.0

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Get Go environment
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"
      - name: Set up cache
        uses: actions/cache@v3.0.8
        with:
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
          key: update-schema-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            update-schema-${{ runner.os }}-go-

      - name: Generate files
        run: make generate

      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@v4.2.0
        with:
          author: GitHub <actions@github.com>
          committer: GitHub <actions@github.com>
          commit-message: 'feat(oas): regenerate BotAPI schema'
          branch: feat/regenerate-schema
          delete-branch: true
          token: ${{ steps.generate-token.outputs.token }}
          title: Re-generate bot API schema
          body: |
            Re-generate bot API schema.
